import type { Metadata } from "next";
import "../globals.css";
import '../fonts.css';
import styles from './style.module.scss';
import {usePathname} from "next/navigation";
import Header from "@/conponents/carriers/Header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <body className={styles.Body}>
        <Header />
        {children}
      </body>
    </html>
  );
}
