import type { Metadata } from "next";
import "../../globals.css";
import "../../fonts.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ServerLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
