import type { Metadata } from "next";
import "../globals.css";
import '../fonts.css';

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children} 
      </body>
    </html>
  );
}
